### ISSUE TITLE
为什么运行的时候报错，编译也不行

### ISSUE THREAD

**Issue by BlueBoyC** [lin-xin/manage-system#3]
![image](https://cloud.githubusercontent.com/assets/10301954/23639146/d9e07f64-0320-11e7-906b-30dc304d350d.png
![image](https://cloud.githubusercontent.com/assets/10301954/23639158/f220fec8-0320-11e7-9348-bcb07cf6f574.png)

**Comment by lin-xin** [comment]
@BlueBoyC 
这个报错信息显示你少了这些项目依赖，你是否有执行 npm install ?可以再执行多一次试试看，如果还是报这样的错，可以检查一下是否node和npm的版本偏低

**Comment by BlueBoyC** [comment]
可以了，原来是npm版本过低，安装的有写问题，我从新弄了之后就正常了，谢谢
