### ISSUE TITLE
之前也搭建类似的，不过有个问题想问一下

### ISSUE THREAD

**Issue by linmodev** [lin-xin/manage-system#5]
因为是现在采用单面应用，那该如何保存用户状态？如果使用sessionStorage？这样安全吗？

**Comment by lin-xin** [comment]
你好，推荐你看一下这个。可以跟你们的后台工程师商量用怎样的解决方法。
https://segmentfault.com/q/1010000007590033

存sessionStorage的话，肯定不安全。

**Comment by linmodev** [comment]
@lin-xin 多谢帮助，想了好久没找到解决办法
