### ISSUE TITLE
对代码有一些问题，希望有空解答一下

### ISSUE THREAD

**Issue by kouguopeng** [lin-xin/manage-system#6]
VueTable.vue这个页面的beforeMount这个方法是写在computed里面，为什么会在页面加载前执行，不是应该在computed外吗？

**Comment by lin-xin** [comment]
@kouguopeng 你好，你是否看错了呢？
`computed:{
            getData(){
                const self = this;
                return self.information.data.filter(function (d) {
                    if(d.name.indexOf(self.query) > -1){
                        return d;
                    }
                })
            }
        },
        beforeMount(){
            axios.get('/static/data.json').then( (res) => {
                this.information = res.data;
            })
        }`
beforeMount并没有写在computed里啊！

**Comment by kouguopeng** [comment]
抱歉我看错了。
