### ISSUE TITLE
项目运行报错，引用文件大小写区分

### ISSUE THREAD

**Issue by liwenlong** [lin-xin/manage-system#7]
其中， 在/src/components/common/Home.vue 中，import的文件名称错了，大小写实际上是区分的
      import vHead from './Header.vue';
      import vSidebar from './Sidebar.vue';
==》
      import vHead from './header.vue';
      import vSidebar from './sidebar.vue';

**Comment by lin-xin** [comment]
@liwenlong ，多谢指出，git 默认忽略了文件名大小写，导致改了名字却没提交。
