### ISSUE TITLE
想换主题

### ISSUE THREAD

**Issue by pimkle** [lin-xin/manage-system#8]
element的切换主题色，下载下来替换上去不是出错，就是不起作用，element下载下来的文件，少了个color-theme.css这样的文件，看起来是不是需要手写啊？

https://elementui.github.io/theme-preview/#/zh-CN

**Comment by lin-xin** [comment]
element下载下来的文件，有个index.css，那个是element组件的颜色，可以替换到/static/css/theme-green/index.css，但是没有用到element组件的地方，想要换颜色还是要自己写的，比如 color-green.css

**Comment by pimkle** [comment]
好的 已经知道了 要是能更自动化就好了🤘🏻
