### ISSUE TITLE
文件名大小写问题

### ISSUE THREAD

**Issue by herryliq** [lin-xin/manage-system#9]
下面的这个路径中文件名大小写有问题，现在git下来是小写的文件名，在Linux下运行时会报错，
应该都是大写的文件。

src/components/common

**Comment by lin-xin** [comment]
@herryliq 你好。之前由于git没区分大小写导致这个问题。我前几天已经修改过了。你是今天clone的还出现这个问题吗？

**Comment by lin-xin** [comment]
#7

**Comment by herryliq** [comment]
@lin-xin 嗯，现在src/components/common这个目录下的文件大小写都有，所以还得再调整一下。
